In [1]:
import numpy as np

In [4]:
a = np.array ([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [3]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [7]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [8]:
np.arange(4)

array([0, 1, 2, 3])

In [9]:
np.arange (0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

In [15]:
arr = np.array([1,2,3,4,5,6,7,8,])

In [16]:
arb = np.append(arr,[1,2])

In [17]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
arb

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [19]:
np.delete(arr,1)

array([1, 3, 4, 5, 6, 7, 8])

In [20]:
arr = np.array([3,4,5,6,6,2,4,2])

In [21]:
np.sort(arr)

array([2, 2, 3, 4, 4, 5, 6, 6])

In [23]:
 array_example = np.array([[[1,2,3,4],[5,6,7,8],[9,10,22,4]]])

In [24]:
array_example

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 22,  4]]])

In [25]:
array_example.ndim

3

In [27]:
array_example.size

12

In [28]:
array_example.shape

(1, 3, 4)

In [29]:
a = np.arange(6)

In [30]:
a

array([0, 1, 2, 3, 4, 5])

In [31]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [32]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [35]:
a = np.array([1,2,3,4,6])

In [36]:
a.shape

(5,)

In [37]:
a2 = a[np.newaxis]

In [38]:
a2

array([[1, 2, 3, 4, 6]])

In [39]:
a2.shape

(1, 5)

In [42]:
row_vector = a[np.newaxis, :1]

In [43]:
row_vector

array([[1]])

In [45]:
col_vector = a[:2 , np.newaxis]

In [46]:
col_vector

array([[1],
       [2]])

In [51]:
b = np.expand_dims(a, axis=1)

In [52]:
b

array([[1],
       [2],
       [3],
       [4],
       [6]])

In [53]:
b.shape

(5, 1)

In [54]:
data = np.array([1,2,3])

In [55]:
print(data[0:2])

[1 2]


In [56]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = [1,2,3]

In [67]:
if 1 in b:
    logic = (a<5)
else:
    logic = (a>5)

In [68]:
a[logic]

array([1, 2, 3, 4])

In [65]:
underseven = (a<7)

In [66]:
a [underseven]

array([1, 2, 3, 4, 5, 6])

In [60]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
a[a>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [69]:
genap = a[a%2==0]
genap

array([ 2,  4,  6,  8, 10, 12])

In [70]:
ganjil = a[a%2!=0]
ganjil

array([ 1,  3,  5,  7,  9, 11])

In [71]:
c = a[(a>2) & (a<11)]
print (c)

[ 3  4  5  6  7  8  9 10]


In [72]:
d = a[(a>2) | (a>5)]
d

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [73]:
f = np.array([1,2,3,4,5])

In [74]:
d = a[(a>2) | (a>5)]
d

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [76]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr1 = arr[3:8]

In [77]:
arr1

array([4, 5, 6, 7, 8])

In [81]:
a_1 = np.array([[1,1],[2,2]])

In [82]:
a_2 = np.array([[3,3],[4,4]])

In [83]:
vs = np.vstack((a_1, a_2))
vs

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [86]:
hs = np.hstack((a_1, a_2))
hs

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [87]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12], [13,14,15,16,17,18,19,20,21,22,23,24]])

In [88]:
arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [89]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [90]:
a = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])

In [91]:
b = a.view()

In [92]:
c = a.copy()

In [93]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [95]:
a = np.array([1,2,3,4])
a.sum()

10

In [96]:
b = np.array([[1,1],[2,2]])
b

array([[1, 1],
       [2, 2]])

In [97]:
b.sum(axis = 0)

array([3, 3])

In [98]:
b.sum(axis = 1)

array([2, 4])

In [99]:
data = np.array([1,2])

In [100]:
ones = np.ones(2)
data

array([1, 2])

In [101]:
ones

array([1., 1.])

In [102]:
data + ones

array([2., 3.])

In [103]:
data * data

array([1, 4])

In [104]:
data * ones

array([1., 2.])

In [105]:
a = np.array([1,2,3,4])

In [106]:
a.max()

4

In [107]:
a.min()

1

In [108]:
a.std()

1.118033988749895

In [109]:
print("Matrix Indexing")

Matrix Indexing


In [110]:
data = np.array([[1,2], [3,4], [5,6]])

In [111]:
print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[1:3])
print(data[0,1])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
[[3 4]
 [5 6]]
2
[2 4]


In [112]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [113]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [115]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [117]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [121]:
np.transpose(data_col)

array([[1, 2, 3, 4, 5, 6]])

In [119]:
arr = np.arange(6).reshape((2,3))

In [120]:
print(arr)

[[0 1 2]
 [3 4 5]]


In [123]:
ndarr = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [124]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [125]:
arrflat = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [127]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [128]:
arrflat.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])